<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="NetBankingV1" duration-ms="49641" started-at="2020-04-18T09:14:07Z" finished-at="2020-04-18T09:14:57Z">
    <groups>
    </groups>
    <test name="BankingApp" duration-ms="49641" started-at="2020-04-18T09:14:07Z" finished-at="2020-04-18T09:14:57Z">
      <class name="com.NetBanking.TestCases.TC_LoginDataDriven_002">
        <test-method status="PASS" signature="Initialization(java.lang.String)[pri:0, instance:com.NetBanking.TestCases.TC_LoginDataDriven_002@3f3afe78]" name="Initialization" is-config="true" duration-ms="13681" started-at="2020-04-18T14:44:08Z" finished-at="2020-04-18T14:44:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initialization -->
        <test-method status="PASS" signature="login_data_driven(java.lang.String, java.lang.String)[pri:0, instance:com.NetBanking.TestCases.TC_LoginDataDriven_002@3f3afe78]" name="login_data_driven" duration-ms="11378" started-at="2020-04-18T14:44:23Z" data-provider="LoginData" finished-at="2020-04-18T14:44:34Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr256248]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[amavYdA]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_data_driven -->
        <test-method status="FAIL" signature="login_data_driven(java.lang.String, java.lang.String)[pri:0, instance:com.NetBanking.TestCases.TC_LoginDataDriven_002@3f3afe78]" name="login_data_driven" duration-ms="5994" started-at="2020-04-18T14:44:34Z" data-provider="LoginData" finished-at="2020-04-18T14:44:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[hsfbchs]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ywsjcbj]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.NetBanking.TestCases.TC_LoginDataDriven_002.login_data_driven(TC_LoginDataDriven_002.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_data_driven -->
        <test-method status="FAIL" signature="login_data_driven(java.lang.String, java.lang.String)[pri:0, instance:com.NetBanking.TestCases.TC_LoginDataDriven_002@3f3afe78]" name="login_data_driven" duration-ms="5688" started-at="2020-04-18T14:44:40Z" data-provider="LoginData" finished-at="2020-04-18T14:44:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[dngjwhs]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hgywissb]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.NetBanking.TestCases.TC_LoginDataDriven_002.login_data_driven(TC_LoginDataDriven_002.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_data_driven -->
        <test-method status="PASS" signature="login_data_driven(java.lang.String, java.lang.String)[pri:0, instance:com.NetBanking.TestCases.TC_LoginDataDriven_002@3f3afe78]" name="login_data_driven" duration-ms="10168" started-at="2020-04-18T14:44:46Z" data-provider="LoginData" finished-at="2020-04-18T14:44:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[mngr256248]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[amavYdA]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_data_driven -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.NetBanking.TestCases.TC_LoginDataDriven_002@3f3afe78]" name="teardown" is-config="true" duration-ms="934" started-at="2020-04-18T14:44:56Z" finished-at="2020-04-18T14:44:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.NetBanking.TestCases.TC_LoginDataDriven_002 -->
    </test> <!-- BankingApp -->
  </suite> <!-- NetBankingV1 -->
</testng-results>
